---
# Один кит на всю жизнь игрока(пока он не умрёт, он не получит новый кит)
one-kit-per-life: false
# Игроки могут взять другой кит, если они перезайдут на сервер (только если включен one-kit-per-life)
reset-on-logout: true
# Добавлять предметы из первого слота инвентаря независимо от того, какой предмет удалится в слоте
start-from-first: false
# Очистить инвентарь игрока перед получением кит набора
clear-inventory: false
# Убрать эффекты игроков перед применением кит набора
clear-effect: false
# Название формы (Главная надпись)
text-on-sign: "[Кит наборы]"
...